samples:
    - ggF
    - VH
    - VBF
    - ttH
    - QCD
    - DYJets
    - WJetsLNu
    - WZQQ
    - TTbar
    - SingleTop
    - Diboson
    - Data

presel:
    ele:
        lep_fj_dr: ( ( lep_fj_dr>0.03) )
    mu:
        lep_fj_dr: ( ( lep_fj_dr>0.03) )


regions_selections:
    pass: ( (inclusive_score>0.90) )
    fail: ( (inclusive_score<0.90) )

    # cat1_sr: ( (inclusive_score>0.9) )
    # tt_cr: ( (inclusive_score<0.90) & (n_bjets_M >=2 ) & (lep_fj_dr>0.3) )
    # wjets_cr: ( (inclusive_score>0.99) & (n_bjets_M < 1) & (lep_fj_dr>0.3) )
    # qcd_cr: (inclusive_score<0.90) & ( ( (lep_pt < 55) & (lep_isolation>0.15)) |  (lep_pt >= 55) ) & ( ( (lep_pt < 55) & (lep_isolation>0.15)) |  (lep_pt >= 55) ),

samples_dir:    # keys here should match the keys above
    pass: ../eos/Jul21_
    fail: ../eos/Sep12_QCD_
