samples:
    - ggF
    - VH
    - VBF
    - ttH
    - QCD
    - DYJets
    - WJetsLNu
    - WZQQ
    - TTbar
    - SingleTop
    - Diboson
    - Data

regions_sel:
    "SR1": (fj_ParT_score_finetuned>0.97) & (n_bjets_T==0)
    "SR2": (fj_ParT_score_finetuned<0.97) & (fj_ParT_score_finetuned>0.85) & (n_bjets_T==0)
    "WJetsCR": (fj_ParT_score_finetuned<0.85) & (fj_ParT_score_finetuned>0.50) & (n_bjets_T==0)
    "TopCR": (fj_ParT_score_finetuned>0.5) & (n_bjets_T>0)

    # fail: ( (fj_ParT_score_finetuned<0.20) & (n_bjets_T == 0) ) # qcd control region
    # wjetsCR: ( (fj_ParT_score_finetuned<0.85) & (fj_ParT_score_finetuned>0.20) & (n_bjets_L == 0) )
    # ttbarCR: ( (fj_ParT_score_finetuned<0.20) & (n_bjets_T > 0) )

lepiso_sel: # keys must match keys in regions_sel above; values are either [lepiso, lepisoinv]
    SR1: lepiso
    SR2: lepiso
    WJetsCR: lepiso
    TopCR: lepiso

    # fail: lepisoinv
    # ttbarCR: lepiso

categories_sel:
    VBFpt200toinf: ( (mjj>1000) & (deta>3.5) )
    ggFpt300toinf: ( (mjj<1000) | (deta<3.5) )

samples_dir:
    "2018": ../eos/postprocessNov12_2018
    "2017": ../eos/postprocessNov12_2017
    "2016APV": ../eos/postprocessNov12_2016APV
    "2016": ../eos/postprocessNov12_2016

model_path: ../eos/model.onnx
