############## FOR BUILDING `events_dict` PURPOSES
samples:
    - ggF
    - VH
    - VBF
    - ttH
    - QCD
    - DYJets
    - WJetsLNu
    - WZQQ
    - TTbar
    - SingleTop
    - Diboson
    - Data

presel:
    ele:
        lepton jet overlap: ( ( lep_fj_dr>0.03) )

        # signal region
        # tagger: ( ( inclusive_score<0.99) )
        # tagger2: ( ( inclusive_score>0.9) )

        # # ttbar region
        # tagger: ( ( inclusive_score<0.9) )
        # b veto: ( ( n_bjets_T>0) )

        # wjets region
        # b veto: ( ( n_bjets_L==0) )

        # qcd region
        tagger: ( ( inclusive_score<0.9) )

    mu:
        lepton jet overlap: ( ( lep_fj_dr>0.03) )

        # signal region
        # tagger: ( ( inclusive_score<0.99) )
        # tagger2: ( ( inclusive_score>0.9) )

        # # ttbar region
        # tagger: ( ( inclusive_score<0.9) )
        # b veto: ( ( n_bjets_T>0) )

        # wjets region
        # b veto: ( ( n_bjets_L==0) )

        # qcd region
        tagger: ( ( inclusive_score<0.9) )

weights:
    ele:
        weight_L1Prefiring: 1
        weight_genweight: 1
        weight_id_electron: 1
        weight_pileup: 1
        weight_reco_electron: 1
        weight_trigger_electron: 1
        weight_vjets_nominal: 1
    mu:
        weight_L1Prefiring: 1
        weight_genweight: 1
        weight_id_muon: 1
        weight_isolation_muon: 1
        weight_pileup: 1
        weight_trigger_iso_muon: 1
        weight_trigger_noniso_muon: 1
        weight_vjets_nominal: 1

############## FOR PLOTTING PURPOSES
vars_to_plot:
    # - fj_minus_lep_m
    # - fj_pt
    # - lep_pt
    # - fj_msoftdrop
    # - fj_bjets_ophem
    # - fj_bjets
    # - lep_fj_dr
    # - lep_met_mt
    # - ht
    # - met_fj_dphi
    # - deta
    # - met
    # - mjj
    - rec_higgs_m
    # - rec_higgs_pt
    # - rec_dphi_WW
    # - fj_ParT_mass
    # - fj_ParticleNet_mass
    # - inclusive_score

samples_to_plot:
    - ggF
    - VH
    - VBF
    - ttH
    - QCD
    - DYJets
    - WJetsLNu
    - WZQQ
    - TTbar
    - SingleTop
    - Diboson
    - Data

# plotting config
add_data: True
logy: False
add_soverb: False
only_sig: False
mult: 1
