#!/usr/bin/python

# when making `events_dict`
samples:
    - HWW
    - VH
    - VBF
    - ttH
    - QCD
    - DYJets
    - WJetsLNu
    - WZQQ
    - TTbar
    - SingleTop
    - Diboson
    - Data

presel:
    ele:
        # fj_pt: ( (fj_pt>220) )
        lep_fj_dr: ( ( lep_fj_dr>0.03) )
    mu:
        # fj_pt: ( (fj_pt>220) )
        lep_fj_dr: ( ( lep_fj_dr>0.03) )

weights:
    ele:
        weight_L1Prefiring: 1
        weight_genweight: 1
        weight_id_electron: 1
        weight_pileup: 1
        weight_reco_electron: 1
        weight_trigger_electron: 1
        weight_vjets_nominal: 1
    mu:
        weight_L1Prefiring: 1
        weight_genweight: 1
        weight_id_muon: 1
        weight_isolation_muon: 1
        weight_pileup: 1
        weight_trigger_iso_muon: 1
        weight_trigger_noniso_muon: 1
        weight_vjets_nominal: 1

regions_selections:
    cat1_sr: ( (inclusive_score>0.99) & (n_bjets_M < 2) & (lep_fj_dr<0.3) )
    tt_cr: ( (inclusive_score<0.90) & (n_bjets_M >=2 ) & (lep_fj_dr>0.3) )
    wjets_cr: ( (inclusive_score>0.99) & (n_bjets_M < 1) & (lep_fj_dr>0.3) )
