#!/usr/bin/python

# when making `events_dict`
samples:
    - HWW
    - VH
    - VBF
    - ttH
    - QCD
    - DYJets
    - WJetsLNu
    - WZQQ
    - TTbar
    - SingleTop
    - Diboson
    - Data

presel:
    ele:
        lepton jet overlap: ( ( lep_fj_dr>0.03) )
    mu:
        lepton jet overlap: ( ( lep_fj_dr>0.03) )

weights:
    ele:
        weight_L1Prefiring: 1
        weight_genweight: 1
        weight_id_electron: 1
        weight_pileup: 1
        weight_reco_electron: 1
        weight_trigger_electron: 1
        weight_vjets_nominal: 1
    mu:
        weight_L1Prefiring: 1
        weight_genweight: 1
        weight_id_muon: 1
        weight_isolation_muon: 1
        weight_pileup: 1
        weight_trigger_iso_muon: 1
        weight_trigger_noniso_muon: 1
        weight_vjets_nominal: 1

# FOR PLOTTING PURPOSES
vars_to_plot:
    - fj_minus_lep_m
    - fj_pt
    - lep_pt
    - fj_msoftdrop
    - fj_bjets_ophem
    - fj_bjets
    - lep_fj_dr
    - lep_met_mt
    - ht
    - met_fj_dphi
    - deta
    - met
    - mjj
    - rec_higgs_m
    - rec_higgs_pt
    - rec_dphi_WW
    # - fj_ParT_mass
    - fj_ParticleNet_mass
    - inclusive_score

samples_to_plot:
    - HWW
    - VH
    - VBF
    - ttH
    - QCD
    - DYJets
    - WJetsLNu
    - WZQQ
    - TTbar
    - SingleTop
    - Diboson
    - Data
